import React, { useState } from 'react';
import { 
  Share2, 
  Bookmark, 
  Check, 
  ChevronUp, 
  ChevronDown, 
  Sparkles, 
  ShieldCheck, 
  Lightbulb, 
  Copy,
  ExternalLink,
  Download,
  FileCode,
  FileText
} from 'lucide-react';
import type { MissionData } from '../types';

interface SynthesisDockProps {
  mission: MissionData;
  onInspectNode: (nodeId: string) => void;
}

export const SynthesisDock: React.FC<SynthesisDockProps> = ({
  mission,
  onInspectNode
}) => {
  const [isExpanded, setIsExpanded] = useState<boolean>(true);
  const [copied, setCopied] = useState<boolean>(false);
  const [bookmarked, setBookmarked] = useState<boolean>(false);
  const [showExportMenu, setShowExportMenu] = useState<boolean>(false);

  const handleCopy = () => {
    if (!mission.result) return;
    navigator.clipboard.writeText(mission.result);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(mission, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `atlantis-mission-${mission.id || 'export'}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    setShowExportMenu(false);
  };

  const handleExportMarkdown = () => {
    const md = `# ATLANTIS AI MISSION DEBRIEF: ${mission.title}
**Sector:** ${mission.sector} | **Topology:** ${mission.topology} | **Status:** ${mission.status.toUpperCase()}
**Execution Time:** ${mission.executionTimeMs || 0}ms | **Nodes Count:** ${mission.nodesCount || 0}
**Certainty Discipline:** Verified across subordinate streams

---

## Final Supervisor Synthesis
${mission.result || 'No output recorded'}

${mission.curiosityFactor ? `\n### Curiosity Factor\n${mission.curiosityFactor}\n` : ''}

---
*Generated by ATLANTIS AI Coordination Intelligence Platform*
`;
    const dataStr = "data:text/markdown;charset=utf-8," + encodeURIComponent(md);
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `atlantis-mission-${mission.id || 'export'}.md`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    setShowExportMenu(false);
  };

  // Clean raw output
  const raw = mission.result || '';
  const certaintyMatch = raw.match(/\[Certainty:\s*([^\]]+)\]/i);
  const certaintyText = certaintyMatch ? certaintyMatch[1] : 'Confirmed across subordinate streams';

  const curiosityMatch = raw.match(/Curiosity Factor:\s*([^\n\r]+)/i);
  const curiosityText = mission.curiosityFactor || (curiosityMatch ? curiosityMatch[1] : null);

  const cleanBody = raw
    .replace(/\[Certainty:[^\]]+\]/i, '')
    .replace(/Curiosity Factor:[^\n\r]+/i, '')
    .trim();

  // Render text with interactive inline citations like [§root-1]
  const renderTextWithCitations = (text: string) => {
    const parts = text.split(/(\[§[a-zA-Z0-9_-]+\])/g);
    return parts.map((part, idx) => {
      const citationMatch = part.match(/\[§([a-zA-Z0-9_-]+)\]/);
      if (citationMatch) {
        const nodeId = citationMatch[1];
        return (
          <button
            key={idx}
            type="button"
            onClick={() => onInspectNode(nodeId)}
            className="inline-flex items-center px-1.5 py-0.5 mx-1 rounded bg-blue-500/15 hover:bg-blue-500/30 text-blue-400 hover:text-blue-200 border border-blue-500/30 font-mono text-[11px] font-bold transition-all"
            title={`Click to inspect source agent [${nodeId}] in tree`}
          >
            §{nodeId}
          </button>
        );
      }
      return <span key={idx}>{part}</span>;
    });
  };

  return (
    <div className="border-t border-zinc-800 bg-zinc-950/95 backdrop-blur-md shadow-2xl transition-all z-20">
      {/* Dock Bar Header */}
      <div className="px-6 py-3 border-b border-zinc-800/80 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="px-2.5 py-1 bg-blue-600 text-white rounded text-[10px] font-mono font-bold uppercase tracking-wider flex items-center gap-1.5 shadow-sm">
            <Sparkles size={12} />
            Supervisor Synthesis
          </div>

          <div className="flex items-center gap-2">
            <h2 className="text-xs font-bold text-zinc-200 uppercase tracking-tight font-mono line-clamp-1">
              MISSION COMPLETE · {mission.sector.toUpperCase()}
            </h2>
            <span className="hidden sm:inline-block px-2 py-0.5 rounded bg-zinc-800 text-[10px] font-mono text-zinc-400 border border-zinc-700/60">
              {mission.topology}
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {/* Plain Certainty Badge */}
          <div className="hidden md:flex items-center gap-1.5 px-2.5 py-1 rounded bg-emerald-500/10 border border-emerald-500/25 text-[11px] font-mono text-emerald-400">
            <ShieldCheck size={13} />
            <span className="line-clamp-1">{certaintyText}</span>
          </div>

          {/* Export Menu */}
          <div className="relative">
            <button
              onClick={() => setShowExportMenu(!showExportMenu)}
              className="p-1.5 text-zinc-400 hover:text-white bg-zinc-900 hover:bg-zinc-800 rounded border border-zinc-800 text-xs flex items-center gap-1 font-mono transition-colors"
              title="Export mission archive"
            >
              <Download size={13} />
              <span className="hidden sm:inline">Export</span>
            </button>

            {showExportMenu && (
              <div className="absolute right-0 bottom-9 bg-zinc-900 border border-zinc-700 rounded-lg shadow-2xl py-1 w-36 text-xs font-mono z-50 animate-fade-in">
                <button
                  onClick={handleExportJSON}
                  className="w-full text-left px-3 py-1.5 text-zinc-300 hover:bg-zinc-800 flex items-center gap-2"
                >
                  <FileCode size={13} className="text-blue-400" />
                  <span>JSON Archive</span>
                </button>
                <button
                  onClick={handleExportMarkdown}
                  className="w-full text-left px-3 py-1.5 text-zinc-300 hover:bg-zinc-800 flex items-center gap-2"
                >
                  <FileText size={13} className="text-emerald-400" />
                  <span>Markdown Brief</span>
                </button>
              </div>
            )}
          </div>

          <button
            onClick={handleCopy}
            className="p-1.5 text-zinc-400 hover:text-white bg-zinc-900 hover:bg-zinc-800 rounded border border-zinc-800 text-xs flex items-center gap-1 font-mono transition-colors"
            title="Copy Final Synthesis"
          >
            {copied ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
            <span className="hidden sm:inline">{copied ? 'Copied' : 'Copy'}</span>
          </button>

          <button
            onClick={() => setBookmarked(!bookmarked)}
            className={`p-1.5 rounded border transition-colors ${
              bookmarked 
                ? 'bg-blue-600 text-white border-blue-500' 
                : 'text-zinc-400 hover:text-white bg-zinc-900 hover:bg-zinc-800 border-zinc-800'
            }`}
            title="Bookmark synthesis"
          >
            <Bookmark size={14} />
          </button>

          <button
            onClick={() => setIsExpanded(!isExpanded)}
            className="p-1.5 text-zinc-400 hover:text-white bg-zinc-900 hover:bg-zinc-800 rounded border border-zinc-800 transition-colors"
            title={isExpanded ? 'Collapse synthesis' : 'Expand synthesis'}
          >
            {isExpanded ? <ChevronDown size={14} /> : <ChevronUp size={14} />}
          </button>
        </div>
      </div>

      {/* Expandable Synthesis Body */}
      {isExpanded && (
        <div className="p-6 max-h-72 overflow-y-auto space-y-4">
          {/* Primary Synthesis Body with interactive citations */}
          <div className="text-sm text-zinc-200 leading-relaxed font-sans whitespace-pre-line max-w-4xl">
            {renderTextWithCitations(cleanBody)}
          </div>

          {/* Curiosity Factor Section */}
          {curiosityText && (
            <div className="mt-4 pt-3 border-t border-zinc-800/80 max-w-4xl">
              <div className="p-3 rounded-lg bg-amber-500/5 border border-amber-500/20 text-xs flex items-start gap-2.5">
                <Lightbulb className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                <div className="space-y-0.5">
                  <div className="text-[10px] font-mono uppercase tracking-wider text-amber-400 font-bold">
                    Curiosity Factor (Adjacent Telemetry)
                  </div>
                  <p className="text-zinc-300 leading-relaxed font-sans">
                    {curiosityText}
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* Supervisor Audit Bar */}
          <div className="pt-3 border-t border-zinc-800/60 flex items-center justify-between text-[11px] font-mono text-zinc-500 max-w-4xl">
            <span>
              CLICK INLINE CITATIONS (§node) TO JUMP TO VERIFIED LEAF SPECIALISTS
            </span>
            <button
              onClick={() => onInspectNode('root')}
              className="text-blue-400 hover:text-blue-300 underline flex items-center gap-1"
            >
              Inspect Root Supervisor Reasoning
              <ExternalLink size={11} />
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
